In [ ]:
import pandas as pd

In [ ]:
df1 = pd.read_excel('kinyert méz 2000-2005.xls')

In [ ]:
df1.rename(columns={'14.14 PRODUCŢIA AGRICOLĂ ANIMALĂ': 'Producţia agricolă animală'}, inplace=True)

In [ ]:
df2 = pd.read_excel('kinyert méz 2006-2011.xls')

In [ ]:
df2.rename(columns={'14.17   Producţia agricolă animală': 'Producţia agricolă animală'  }, inplace=True)

In [ ]:
df3 = pd.read_excel('kinyert méz 2012-2017.xls')

In [ ]:
df3.rename(columns={'14.18   Producţia agricolă animală': 'Producţia agricolă animală' }, inplace=True)

In [ ]:
df4 = pd.read_excel('kinyert méz 2018-2020.xls')

In [ ]:
df4.rename(columns={'14.16   Producţia agricolă animală': 'Producţia agricolă animală' }, inplace=True)

In [ ]:
df5 = pd.read_excel('kinyert méz 2021-2022.xls')

In [ ]:
df5.rename(columns={'14.16   Producţia agricolă animală': 'Producţia agricolă animală' }, inplace=True)

In [ ]:
mdf=pd.merge(df1,df2, on=('Animale ce revin la 100 hectare teren'), how='inner')

In [ ]:
mdf.rename(columns={'Animale ce revin la 100 hectare teren': 'Producţia agricolă animală'}, inplace=True)

In [ ]:
mdf=pd.merge(mdf,df4, on=('Producţia agricolă animală'), how='inner')

In [ ]:
mdf=pd.merge(mdf,df5, on=('Producţia agricolă animală'), how='inner')

MergeError: Passing 'suffixes' which cause duplicate columns {'Unnamed: 4_x', 'Unnamed: 1_x', 'Unnamed: 2_x', 'Unnamed: 7_x', 'Unnamed: 6_x', 'Unnamed: 5_x', 'Unnamed: 3_x'} is not allowed.

az elso 3 tablazatot osszeteszi majd kitorli a teljesen ures sorokat

In [ ]:
cdf1 = pd.concat([df1, df2, df3], axis=1)
cdf1 = cdf1.dropna(axis=1, how='all')
cdf1=cdf1.dropna(axis=0, how='all')

kivalogatja, hogy csak a lenyeges sorok maradjanak

In [ ]:
mez_00_17 = pd.concat([cdf1.iloc[1:3], cdf1.iloc[30:31]])

a din care: felirat utan odahelyezi a cella jo tartalmat

In [ ]:
for i, row in mez_00_17.iterrows():
    for j, cell in enumerate(row):
        if cell == 'din care:':
            row[j] += " proprietate majoritar privata"

In [ ]:
cdf2 = pd.concat([df4, df5], axis=1)
cdf2 = cdf2.dropna(axis=1, how='all')
cdf2 = cdf2.dropna(axis=0, how='all')

In [ ]:
mez_18_22 = pd.concat([cdf2.iloc[1:3], cdf2.iloc[50:51]])

In [ ]:
for i, row in mez_18_22.iterrows():
    for j, cell in enumerate(row):
        if cell == 'din care:':
            row[j] += " proprietate majoritar privata"

In [ ]:
mez_00_22 = pd.concat([mez_00_17.reset_index(drop=True), mez_18_22.reset_index(drop=True)], axis=1)

In [ ]:
mez_00_22

,14.14 PRODUCŢIA AGRICOLĂ ANIMALĂ,Unnamed: 1,Unnamed: 3,Unnamed: 4,Unnamed: 6,Unnamed: 7,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,...,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,14.16 Producţia agricolă animală,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,U.M.,2000,NaN,2001,NaN,2002,NaN,2003,NaN,...,2019,NaN,2020,NaN,NaN,U.M. / M.U.,2021,NaN,2022,NaN
1,,NaN,Total,din care:,Total,din care:,Total,din care:,Total,din care:,...,Total,din care:,Total,din care:,,NaN,Total,din care:,Total,din care:
2,Miere extrasă,tone,11746,11617,12598,12515,13434,13398,17409,17343,...,25269,25258,30714,30704,Miere extrasă,tone,30831,30823,29760,29751

megfordítja a táblázatot

In [ ]:
mez_megforditott = mez_00_22.transpose()

kitörli azokat a sorokat ahol az utolso oszlopban nem szám szerepel

In [ ]:
mez_megforditott = mez_megforditott[pd.to_numeric(mez_megforditott[2], errors='coerce').notna()]

átírja a szoveget a kivalasztott cellában (0-tol számolja)

In [ ]:
mez_megforditott.iloc[8, 0] = "2004"#2005re is

In [ ]:
mez_megforditott['Év'] = pd.to_numeric(mez_megforditott['Év'])

In [ ]:
mez_megforditott[0].fillna(method='ffill', inplace=True)

In [ ]:
mez_megforditott.loc[mez_megforditott[1] == 'din care:', 1] = 'ebből: többnyire magántulajdon'

In [ ]:
mez_megforditott.rename(columns={0: 'Év'}, inplace=True)
mez_megforditott.rename(columns={1: 'Össz'}, inplace=True)
mez_megforditott.rename(columns={2: 'Kinyert méz (tonna)'}, inplace=True)
mez_megforditott.reset_index(drop=True, inplace=True)

In [ ]:
mez_megforditott

      Év                            Össz Kinyert méz (tonna)
0   2000                           Total               11746
1   2000  ebből: többnyire magántulajdon               11617
2   2001                           Total               12598
3   2001  ebből: többnyire magántulajdon               12515
4   2002                           Total               13434
5   2002  ebből: többnyire magántulajdon               13398
6   2003                           Total               17409
7   2003  ebből: többnyire magántulajdon               17343
8   2004                           Total               19150
9   2004  ebből: többnyire magántulajdon               19112
10  2005                           Total               17704
11  2005  ebből: többnyire magántulajdon               17637
12  2006                           Total               18195
13  2006  ebből: többnyire magántulajdon               18184
14  2007                           Total               16767
15  2007  ebből: többnyire magántulajdon               16758
16  2008                           Total               20037
17  2008  ebből: többnyire magántulajdon               20028
18  2009                           Total               19937
19  2009  ebből: többnyire magántulajdon               19924
20  2010                           Total               22222
21  2010  ebből: többnyire magántulajdon               22203
22  2011                           Total               24127
23  2011  ebből: többnyire magántulajdon               24112
24  2012                           Total               23062
25  2012  ebből: többnyire magántulajdon               23053
26  2013                           Total               26678
27  2013  ebből: többnyire magántulajdon               26674
28  2014                           Total               18040
29  2014  ebből: többnyire magántulajdon               18036
30  2015                           Total               27893
31  2015  ebből: többnyire magántulajdon               27883
32  2016                           Total               21202
33  2016  ebből: többnyire magántulajdon               21194
34  2017                           Total               30177
35  2017  ebből: többnyire magántulajdon               30168
36  2018                           Total               29162
37  2018  ebből: többnyire magántulajdon               29152
38  2019                           Total               25269
39  2019  ebből: többnyire magántulajdon               25258
40  2020                           Total               30714
41  2020  ebből: többnyire magántulajdon               30704
42  2021                           Total               30831
43  2021  ebből: többnyire magántulajdon               30823
44  2022                           Total               29760
45  2022  ebből: többnyire magántulajdon               29751

In [ ]:
mez_megforditott.to_excel('kinyertmez.xlsx')

In [ ]:
mez_megforditott.to_csv('kinyertmez.csv')

In [ ]:
df= pd.read_excel('kinyertmez.xlsx')

In [ ]:
df['Év'] = pd.to_datetime(df['Év'], format='%Y').dt.year

In [ ]:
df

    Unnamed: 0    Év                            Össz  Kinyert méz (tonna)
0            0  2000                           Total                11746
1            1  2000  ebből: többnyire magántulajdon                11617
2            2  2001                           Total                12598
3            3  2001  ebből: többnyire magántulajdon                12515
4            4  2002                           Total                13434
5            5  2002  ebből: többnyire magántulajdon                13398
6            6  2003                           Total                17409
7            7  2003  ebből: többnyire magántulajdon                17343
8            8  2004                           Total                19150
9            9  2004  ebből: többnyire magántulajdon                19112
10          10  2005                           Total                17704
11          11  2005  ebből: többnyire magántulajdon                17637
12          12  2006                           Total                18195
13          13  2006  ebből: többnyire magántulajdon                18184
14          14  2007                           Total                16767
15          15  2007  ebből: többnyire magántulajdon                16758
16          16  2008                           Total                20037
17          17  2008  ebből: többnyire magántulajdon                20028
18          18  2009                           Total                19937
19          19  2009  ebből: többnyire magántulajdon                19924
20          20  2010                           Total                22222
21          21  2010  ebből: többnyire magántulajdon                22203
22          22  2011                           Total                24127
23          23  2011  ebből: többnyire magántulajdon                24112
24          24  2012                           Total                23062
25          25  2012  ebből: többnyire magántulajdon                23053
26          26  2013                           Total                26678
27          27  2013  ebből: többnyire magántulajdon                26674
28          28  2014                           Total                18040
29          29  2014  ebből: többnyire magántulajdon                18036
30          30  2015                           Total                27893
31          31  2015  ebből: többnyire magántulajdon                27883
32          32  2016                           Total                21202
33          33  2016  ebből: többnyire magántulajdon                21194
34          34  2017                           Total                30177
35          35  2017  ebből: többnyire magántulajdon                30168
36          36  2018                           Total                29162
37          37  2018  ebből: többnyire magántulajdon                29152
38          38  2019                           Total                25269
39          39  2019  ebből: többnyire magántulajdon                25258
40          40  2020                           Total                30714
41          41  2020  ebből: többnyire magántulajdon                30704
42          42  2021                           Total                30831
43          43  2021  ebből: többnyire magántulajdon                30823
44          44  2022                           Total                29760
45          45  2022  ebből: többnyire magántulajdon                29751

In [ ]:
df.to_excel('kinyertmezev.xlsx')